

<?php
$email= strip_tags($_POST['emailx']);
$fullname= strip_tags($_POST['fullnamex']);
$em_title= strip_tags($_POST['em_title']);
$email_message= strip_tags($_POST['email_message']);
$chatgpt_message= strip_tags($_POST['chatgpt_message']);

?>

  <script src="jquery.min.js"></script>

<script>


$(document).ready(function(){
$('.nylas_ny_btn').click(function(){
		
var emailx = '<?php echo $email; ?>';
var fullnamex = '<?php echo $fullname; ?>';;
var em_title = $('.subjectx').val();
var email_message = $('.generated_messagex').val();

if(em_title==""){
alert('Email Subject Cannot be Empty');
}

else if(email_message==""){
alert('Please Click on Optimize Email Button to Optimize Email Before Sending');
}

else{

$('#loader_ny').fadeIn(400).html('<br><div style="color:black;background:#ddd;padding:10px;"><img src="ajax-loader.gif">&nbsp;Please Wait, Sending Email via NYLAS API...</div>');
var datasend = {emailx:emailx,fullnamex:fullnamex, em_title:em_title, email_message:email_message};	
		$.ajax({
			
			type:'POST',
			url:'nylas_email_send.php',
			data:datasend,
                        crossDomain: true,
			cache:false,
			success:function(msg){
                        $('#loader_ny').hide();
                        $('#result_ny').fadeIn('slow').html(msg);
//setTimeout(function(){ $('#result_ny').html(''); }, 9000);


//strip all html elemnts using jquery
var html_stripped = jQuery(msg).text();
//check occurrence of word (successful) from backend output already html stripped.
var Frombackend = html_stripped;
var bcount = (Frombackend.match(/successful/g) || []).length;
if(bcount > 0){
//$('.email_message').val('');
//$('.em_title').val('');
}


			}
			
		});
		
		}
		
	})
					
});


</script>


<script>
$(document).ready(function(){
function copyHandler() {
    var copyVal = document.getElementById("generated_messagex2").value;
    var replaceInput = document.getElementById("generated_messagex");



    replaceInput.value = copyVal;
}

document.getElementById("copy-down1").onclick = function(){

var copyValx = document.getElementById("generated_messagex2").value;
if(copyValx==""){
alert('Enter Email Text Message Generated by ChatGPT First');
return false;
}

alert('Nylas Email Successfully Optimized.. Email is Now Ready to be Sent...');
$('#result_emx_1').fadeIn('slow').html("<div style='background:fuchsia;color:white;padding:4px;border:none;'>Nylas Email Successfully Optimized.. Email is Now Ready to be Sent...</div>");
    copyHandler();
    return false;

}

});
</script>


<?php


ini_set('max_execution_time', 300); //300 seconds = 5 minutes
// temporarly extend time limit
set_time_limit(300);

//error_reporting(0);


if (isset($_POST) and $_SERVER['REQUEST_METHOD'] == "POST") {

include('settings.php');



if($nylas_accesstoken ==''){
echo "<div  style='background:red;color:white;padding:10px;border:none;'>Please Ask Admin to Set Nylas API Access Token  at <b>settings.php</b> File</div><br>";
exit();

}


if($chatgpt_accesstoken ==''){
echo "<div  style='background:red;color:white;padding:10px;border:none;'>Please Ask Admin to Set Chatgpt Access Token at <b>settings.php</b> File</div><br>";
exit();

}

// Make API Call to ChatGPT AI


$url ="https://api.openai.com/v1/completions";
$data_param ='
{
   "model" : "text-davinci-003",
    "prompt":  "'.$chatgpt_message.'",
    "max_tokens": 300,
"n": 1
}
';


$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_POST, TRUE);
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json', "Authorization: Bearer $chatgpt_accesstoken"));  
curl_setopt($ch, CURLOPT_POSTFIELDS, $data_param);
//curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
$output = curl_exec($ch); 

if($output == ''){
echo "<div style='background:red;color:white;padding:10px;border:none;'>API Call to Chatgpt AI Failed. Ensure there is an Internet  Connections...</div><br>";
exit();
}




$http_status = curl_getinfo($ch, CURLINFO_HTTP_CODE);

// catch error message before closing
if (curl_errno($ch)) {
   // echo $error_msg = curl_error($ch);
}

curl_close($ch);


$json = json_decode($output, true);
$id = $json["id"];

$mx_error = $json["error"]["message"];
if($mx_error != ''){
echo "<div style='background:red;color:white;padding:10px;border:none;'>Chatgpt API Error Message: $mx_error.</div><br>";
exit();
}


if($id != ''){

echo "<div style='color:white;background:green;padding:10px;'>Drug Prescription Successfully Generated Via Chatgpt AI. See Below</div>";

}
else {
echo "<div style='color:white;background:red;padding:10px;'>There is an Issue Generating Drug Prescription Via Chatgpt AI. Please Check Internet Connections</div>";
exit();

}   

$countx= 1;

echo "<div class='row'>
<div class='col-sm-1'></div> 
<div class='col-sm-10 well'>
<h4>ChatGPT Generated Patients Drug Prescription to be send to Patients Email Address</h4>";


foreach($json['choices'] as $row){
$countxx = $countx++;

$val = $row["text"];
$val2 = str_replace(',', ',<br>', $val);
$value = str_replace('.', '<br>', $val2);

//echo "<span><b>$countxx.)</b> $value</span><br><br>";

echo "

 <br><div class='form-group'>
              <label>Enter Email Subject </label>
              <input type='text' class='col-sm-12 form-control subjectx'  placeholder='Enter Email Subject' value='Here is Your Drug Prescriptions powered by ChatGPT AI'>
            </div><br>

<div class='form-group'>
<label> Message </label>
<textarea cols='10' id='generated_messagex2' rows='10' class='form-control generated_messagex2' >$val</textarea>

<div id='result_emx_1'></div>
<input type='submit' id='copy-down1' class='btn btn-warning btn-xs' value='Optimize Nylas Email Message Before Sending'>

<input style='width:10px;height:5px;' type='text' name='' id='generated_messagex' class='form-control generated_messagex' placeholder='Enter Email Message Generated by ChatGPT'><br><br>

</div>

";



}
echo "

<div class='form-group'>                  
<div id='loader_ny'></div>
<div id='result_ny'></div>
</div>

<div class='form-group'> 
<button type='button; id='nylas_ny_btn' class='nylas_ny_btn btn btn-primary'  >Send Medical Data to Patients Email Via Nylas</button><br><br>
</div>






</div>
<div class='col-sm-1'></div> 
</div>";




}
else{
echo "<div id='' style='background:red;color:white;padding:10px;border:none;'>
Direct Page Access not Allowed<br></div>";
}


?>
